export const mysteryAssets = {
  homeHero: require('../../assets/art/home-hotel-hero.png'),
  mapBackgroundWood: require('../../assets/art/map-background-wood-panel.png'),
  mapBlueprint: require('../../assets/art/map-hotel-blueprint.png'),
  rooms: {
    reception: require('../../Assets-art/room-reception.png'),
    room: require('../../assets/art/room-collector.png'),
    office: require('../../assets/art/room-office.png'),
    auction: require('../../assets/art/room-auction.png'),
    secret: require('../../assets/art/room-secret.png'),
    room214: require('../../Assets-art/room-214.png'),
    restaurant: require('../../Assets-art/room-restaurant.png'),
    lobbyBar: require('../../Assets-art/room-lobby-bar.png'),
    winterGarden: require('../../Assets-art/room-winter-garden.png'),
    library: require('../../Assets-art/room-library.png'),
    banquetHall: require('../../Assets-art/room-banquet-hall.png'),
    gallery: require('../../Assets-art/room-gallery.png'),
    corridorFloor2: require('../../Assets-art/room-corridor-flor-2.png'),
    sideStairs: require('../../Assets-art/room-side-stair.png'),
    hotelOffice: require('../../Assets-art/room-hotel-office.png'),
    telephoneSwitchboard: require('../../Assets-art/room-telephone-switch.png'),
    laundry: require('../../Assets-art/room-laundry.png'),
    kitchenCorridor: require('../../Assets-art/room-kitchen-corridor.png'),
    serviceElevator: require('../../Assets-art/room-service-elevator.png'),
    guestArchive: require('../../Assets-art/room-guest-archive.png'),
    billingArchive: require('../../Assets-art/room-billing-archive.png'),
    keyStorage: require('../../Assets-art/room-key-storage.png'),
    staffRoom: require('../../Assets-art/room-staff-room.png'),
    managerOffice: require('../../Assets-art/room-manager-office.png'),
    elevatorMachineRoom: require('../../Assets-art/room-elevator-machine-room.png'),
    closedWing: require('../../Assets-art/room-closed-wing.png'),
    room214Return: require('../../Assets-art/room-214-return.png'),
  },
  clues: {
    key101: require('../../assets/art/clue-key-101.png'),
    envelope: require('../../assets/art/clue-envelope.png'),
    catalog: require('../../assets/art/katalog.png'),
    plan: require('../../assets/art/plan.png'),
    auctionLabel: require('../../assets/art/aukcni-stitek.png'),
    medallion: require('../../assets/art/samostatny-medailon.png'),
    roomCard214: require('../../Assets-art/clue-room-card-214.png'),
    hotelNotebook: require('../../Assets-art/clue-hotel-notebook.png'),
    oldMenu: require('../../Assets-art/clue-old-menu.png'),
    barReceipt: require('../../Assets-art/clue-bar-receipt.png'),
    oldPhotograph: require('../../Assets-art/clue-old-photo.png'),
    libraryCard: require('../../Assets-art/clue-library-card.png'),
    guestList: require('../../Assets-art/clue-guest-list.png'),
    croppedPhoto: require('../../Assets-art/clue-cropped-photo.png'),
    mapFragment: require('../../Assets-art/clue-map-fragment.png'),
    oldServiceKey: require('../../Assets-art/clue-old-key.png'),
    internalNote: require('../../Assets-art/clue-internal-note.png'),
    callRecord: require('../../Assets-art/clue-call-record.png'),
    coatTag: require('../../Assets-art/clue-coat-tag.png'),
    nightShiftSheet: require('../../Assets-art/clue-night-shift-sheet.png'),
    serviceSlip: require('../../Assets-art/clue-service-slip.png'),
    guestBook: require('../../Assets-art/clue-guest-book.png'),
    closedBill: require('../../Assets-art/clue-closed-bill.png'),
    spareKey: require('../../Assets-art/clue-spare-key.png'),
    shiftSchedule: require('../../Assets-art/clue-shift-schedule.png'),
    managerNote: require('../../Assets-art/clue-manager-note.png'),
    oldMap: require('../../Assets-art/clue-old-map.png'),
    mechanicalRecord: require('../../Assets-art/clue-mechanical-record.png'),
    forgottenSuitcase: require('../../Assets-art/clue-forgotten-suitcase.png'),
    notebook: require('../../Assets-art/clue-notebook.png'),
    finalPage: require('../../Assets-art/clue-final-page.png'),
  },
  chapterReveals: {
    part01: require('../../Assets-art/chapter-reveal-part-01.png'),
    part02: require('../../Assets-art/chapter-reveal-part-02.png'),
    part03: require('../../Assets-art/chapter-reveal-part-03.png'),
    part04: require('../../Assets-art/chapter-reveal-part-04.png'),
    part05: require('../../Assets-art/chapter-reveal-part-05.png'),
  },
  textures: {
    parchment: require('../../assets/art/texture-parchment.png'),
  },
} as const;

export type RoomAssetKey = keyof typeof mysteryAssets.rooms;

export function getRewardAsset(rewardId: string) {
  switch (rewardId) {
    case 'brass-key':
    case 'key':
    case 'key101':
    case 'room-card-214':
    case 'roomCard214':
    case 'clue-room-card-214':
    case 'stop-01':
      return mysteryAssets.clues.roomCard214;
    case 'hotel-notebook':
    case 'hotelNotebook':
    case 'clue-hotel-notebook':
    case 'stop-02':
      return mysteryAssets.clues.hotelNotebook;
    case 'old-menu':
    case 'oldMenu':
    case 'clue-old-menu':
    case 'stop-03':
      return mysteryAssets.clues.oldMenu;
    case 'bar-receipt':
    case 'barReceipt':
    case 'clue-bar-receipt':
    case 'stop-04':
      return mysteryAssets.clues.barReceipt;
    case 'old-photograph':
    case 'oldPhotograph':
    case 'clue-old-photograph':
    case 'clue-old-photo':
    case 'stop-05':
      return mysteryAssets.clues.oldPhotograph;
    case 'library-card':
    case 'libraryCard':
    case 'clue-library-card':
    case 'stop-06':
      return mysteryAssets.clues.libraryCard;
    case 'guest-list':
    case 'guestList':
    case 'clue-guest-list':
    case 'stop-07':
      return mysteryAssets.clues.guestList;
    case 'cropped-photo':
    case 'croppedPhoto':
    case 'clue-cropped-photo':
    case 'stop-08':
      return mysteryAssets.clues.croppedPhoto;
    case 'map-fragment':
    case 'mapFragment':
    case 'clue-map-fragment':
    case 'stop-09':
      return mysteryAssets.clues.mapFragment;
    case 'old-key':
    case 'oldServiceKey':
    case 'clue-old-key':
    case 'stop-10':
      return mysteryAssets.clues.oldServiceKey;
    case 'internal-note':
    case 'internalNote':
    case 'clue-internal-note':
    case 'stop-11':
      return mysteryAssets.clues.internalNote;
    case 'call-record':
    case 'callRecord':
    case 'clue-call-record':
    case 'stop-12':
      return mysteryAssets.clues.callRecord;
    case 'coat-tag':
    case 'coatTag':
    case 'clue-coat-tag':
    case 'stop-13':
      return mysteryAssets.clues.coatTag;
    case 'night-shift-sheet':
    case 'nightShiftSheet':
    case 'clue-night-shift-sheet':
    case 'stop-14':
      return mysteryAssets.clues.nightShiftSheet;
    case 'service-slip':
    case 'serviceSlip':
    case 'clue-service-slip':
    case 'stop-15':
      return mysteryAssets.clues.serviceSlip;
    case 'guest-book':
    case 'guestBook':
    case 'clue-guest-book':
    case 'stop-16':
      return mysteryAssets.clues.guestBook;
    case 'closed-bill':
    case 'closedBill':
    case 'clue-closed-bill':
    case 'stop-17':
      return mysteryAssets.clues.closedBill;
    case 'spare-key':
    case 'spareKey':
    case 'clue-spare-key':
    case 'stop-18':
      return mysteryAssets.clues.spareKey;
    case 'shift-schedule':
    case 'shiftSchedule':
    case 'clue-shift-schedule':
    case 'stop-19':
      return mysteryAssets.clues.shiftSchedule;
    case 'manager-note':
    case 'managerNote':
    case 'clue-manager-note':
    case 'stop-20':
      return mysteryAssets.clues.managerNote;
    case 'old-map':
    case 'oldMap':
    case 'clue-old-map':
    case 'stop-21':
      return mysteryAssets.clues.oldMap;
    case 'mechanical-record':
    case 'mechanicalRecord':
    case 'clue-mechanical-record':
    case 'stop-22':
      return mysteryAssets.clues.mechanicalRecord;
    case 'forgotten-suitcase':
    case 'forgottenSuitcase':
    case 'clue-forgotten-suitcase':
    case 'stop-23':
      return mysteryAssets.clues.forgottenSuitcase;
    case 'notebook':
    case 'clue-notebook':
    case 'stop-24':
      return mysteryAssets.clues.notebook;
    case 'final-page':
    case 'finalPage':
    case 'clue-final-page':
    case 'stop-25':
      return mysteryAssets.clues.finalPage;
    case 'legacy-key101':
      return mysteryAssets.clues.key101;
    case 'catalog-fragment':
    case 'catalog':
      return mysteryAssets.clues.catalog;
    case 'old-plan':
    case 'plan':
      return mysteryAssets.clues.plan;
    case 'auction-label':
    case 'label':
    case 'auctionLabel':
      return mysteryAssets.clues.auctionLabel;
    case 'letter-medallion':
    case 'medallion':
      return mysteryAssets.clues.medallion;
    default:
      if (rewardId.includes('01') || rewardId.includes('06') || rewardId.includes('11') || rewardId.includes('16') || rewardId.includes('21')) {
        return mysteryAssets.clues.key101;
      }
      if (rewardId.includes('02') || rewardId.includes('07') || rewardId.includes('12') || rewardId.includes('17') || rewardId.includes('22')) {
        return mysteryAssets.clues.catalog;
      }
      if (rewardId.includes('03') || rewardId.includes('08') || rewardId.includes('13') || rewardId.includes('18') || rewardId.includes('23')) {
        return mysteryAssets.clues.plan;
      }
      if (rewardId.includes('04') || rewardId.includes('09') || rewardId.includes('14') || rewardId.includes('19') || rewardId.includes('24')) {
        return mysteryAssets.clues.auctionLabel;
      }
      return mysteryAssets.clues.medallion;
  }
}
